<a href="https://colab.research.google.com/github/rakesh-mandal/ML/blob/main/day40-Interative%20Imputer/day40_MICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
# 1. You must explicitly enable IterativeImputer first
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [ ]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [ ]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/tmp/ipykernel_3646/766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipykernel_3646/766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipykernel_3646/766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [ ]:
df.shape

(5, 3)

In [ ]:
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [ ]:
# 2. Initialize the imputer matching your manual settings
imputer = IterativeImputer(
    estimator=LinearRegression(), # Switch from default BayesianRidge to match your notebook
    max_iter=2,                   # Number of iterations
    initial_strategy='mean',      # 0th iteration baseline
    imputation_order='roman',     # Process columns left-to-right index order
    random_state=9
)

In [ ]:
# 3. Fit and transform the data
imputed_array = imputer.fit_transform(df)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [ ]:
imputed_array

array([[ 8.        , 15.        , 30.        ],
       [23.82870339,  5.        , 20.        ],
       [15.        , 10.        , 41.        ],
       [12.        , 11.23073734, 26.        ],
       [ 2.        , 15.        , 39.3904363 ]])

In [ ]:
# Convert back to a readable DataFrame
df_imputed = pd.DataFrame(imputed_array, columns=df.columns)
print(np.round(df_imputed, 2))

   R&D Spend  Administration  Marketing Spend
0       8.00           15.00            30.00
1      23.83            5.00            20.00
2      15.00           10.00            41.00
3      12.00           11.23            26.00
4       2.00           15.00            39.39