<a href="https://colab.research.google.com/github/rakesh-mandal/ML/blob/main/day59-Classification%20metric/Classification_metrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/heart.csv')

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf1 = LogisticRegression(max_iter=1000)
clf1.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred1 = clf1.predict(X_test_scaled)
y_pred2 = clf2.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8688524590163934
Accuracy of Decision Trees 0.8360655737704918

In [ ]:
from sklearn.metrics import confusion_matrix

print("Logistic Regression")
print(confusion_matrix(y_test, y_pred1))

print("\nDecision Tree")
print(confusion_matrix(y_test, y_pred2))

Logistic Regression
[[25  7]
 [ 1 28]]

Decision Tree
[[24  8]
 [ 2 27]]

In [ ]:
from sklearn.metrics import confusion_matrix

# Logistic Regression
cm_lr = confusion_matrix(y_test, y_pred1)

df_cm_lr = pd.DataFrame(
    cm_lr,
    index=['Actual 0', 'Actual 1'],
    columns=['Predicted 0', 'Predicted 1']
)

print("Logistic Regression")
print(df_cm_lr)

# Decision Tree
cm_dt = confusion_matrix(y_test, y_pred2)

df_cm_dt = pd.DataFrame(
    cm_dt,
    index=['Actual 0', 'Actual 1'],
    columns=['Predicted 0', 'Predicted 1']
)

print("\nDecision Tree")
print(df_cm_dt)

Logistic Regression
          Predicted 0  Predicted 1
Actual 0           25            7
Actual 1            1           28

Decision Tree
          Predicted 0  Predicted 1
Actual 0           24            8
Actual 1            2           27

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
print("Precision - ",precision_score(y_test,y_pred1))

Precision -  0.8

In [ ]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [ ]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  25   7
1   1  28
--------------------------------------------------
Precision -  0.8
Recall -  0.9655172413793104
F1 score -  0.875

In [ ]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  24   8
1   2  27
--------------------------------------------------
Precision -  0.7714285714285715
Recall -  0.9310344827586207
F1 score -  0.84375

In [ ]:
from sklearn.metrics import classification_report

print("Logistic Regression")
print(classification_report(y_test, y_pred1))

print("Decision Tree")
print(classification_report(y_test, y_pred2))

Logistic Regression
              precision    recall  f1-score   support

           0       0.96      0.78      0.86        32
           1       0.80      0.97      0.88        29

    accuracy                           0.87        61
   macro avg       0.88      0.87      0.87        61
weighted avg       0.88      0.87      0.87        61

Decision Tree
              precision    recall  f1-score   support

           0       0.92      0.75      0.83        32
           1       0.77      0.93      0.84        29

    accuracy                           0.84        61
   macro avg       0.85      0.84      0.84        61
weighted avg       0.85      0.84      0.84        61

In [ ]:
precision_score(y_test,y_pred1,average=None)

array([0.96153846, 0.8       ])

In [ ]:
"""
Let's go through the classification report line by line. Your confusion matrix was:

	Predicted 0	Predicted 1
Actual 0	25	7
Actual 1	1	28

From this:

TP (class 1) = 28
FP (class 1) = 7
FN (class 1) = 1
TN (class 1) = 25


Classification Report
              precision    recall  f1-score   support

           0       0.96      0.78      0.86        32
           1       0.80      0.97      0.88        29

Scikit-learn treats each class as the positive class once.

Class 0

Here, class 0 is considered the positive class.

So,

TP = 25
FP = 1
FN = 7
Precision (Class 0)
Precision
0
	​

=
25+1
25
	​

=
26
25
	​

=0.9615

≈ 0.96

Meaning: Whenever the model predicts No Heart Disease (0), it is correct 96% of the time.

Recall (Class 0)
Recall
0
	​

=
25+7
25
	​

=
32
25
	​

=0.78125

≈ 0.78

Meaning: Out of all 32 patients who actually had No Heart Disease, the model correctly identified 25.

F1-score (Class 0)
F1=
P+R
2PR
	​


Substitute

P=0.96,R=0.78
F1=
0.96+0.78
2(0.96)(0.78)
	​

=0.86
Class 1

Now class 1 is considered the positive class.

TP = 28
FP = 7
FN = 1
Precision
28+7
28
	​

=0.80

This means:

When the model predicts Heart Disease, it is correct 80% of the time.

Recall
28+1
28
	​

=0.9655

≈ 0.97

Meaning:

Out of 29 patients who actually have heart disease, the model correctly found 28.

Only 1 patient was missed.

F1-score
F1=
0.80+0.97
2(0.80)(0.97)
	​

=0.88
Support
support

0   32
1   29

Support is simply the number of actual samples belonging to each class.

32 patients actually belong to class 0.
29 patients actually belong to class 1.

Total

32+29=61

which matches your test set size.

Accuracy
accuracy 0.87

Accuracy is

Total
TP+TN
	​

=
61
28+25
	​

=
61
53
	​

=0.869

≈ 87%

So the model correctly classified 53 out of 61 patients.

Macro Average
macro avg
precision 0.88
recall    0.87
f1-score  0.87

Macro average is the simple average of the metrics for each class.

Precision:

2
0.96+0.80
	​

=0.88

Recall:

2
0.78+0.97
	​

=0.875≈0.87

F1:

2
0.86+0.88
	​

=0.87

Each class contributes equally, regardless of how many samples it has.

Weighted Average
weighted avg
precision 0.88
recall    0.87
f1-score  0.87

Weighted average uses the support of each class as weights.

For precision:

61
(0.96×32)+(0.80×29)
	​

=0.88

Since your classes are nearly balanced (32 vs. 29), the weighted averages are very close to the macro averages.

What does this report tell you?
Accuracy = 87%: The model performs well overall.
Class 1 (heart disease) has very high recall (97%): the model misses very few heart disease cases (only 1 false negative). This is often desirable in medical diagnosis because missing a patient with the disease can have serious consequences.
Class 1 precision is 80%: about 20% of the patients predicted to have heart disease are actually healthy (false positives).
Class 0 precision is 96%: when the model predicts "no heart disease," it is almost always correct.
Class 0 recall is 78%: the model incorrectly labels some healthy patients as having heart disease (7 false positives from the perspective of class 1).

Overall, your Logistic Regression model is biased toward detecting heart disease, resulting in high recall for class 1 at the cost of a moderate number of false alarms. In a medical screening setting, this trade-off is often preferred because it is generally safer to investigate a healthy patient further than to miss someone who actually has the disease.
"""

'\nLet\'s go through the classification report line by line. Your confusion matrix was:\n\n\tPredicted 0\tPredicted 1\nActual 0\t25\t7\nActual 1\t1\t28\n\nFrom this:\n\nTP (class 1) = 28\nFP (class 1) = 7\nFN (class 1) = 1\nTN (class 1) = 25\n\n\nClassification Report\n              precision    recall  f1-score   support\n\n           0       0.96      0.78      0.86        32\n           1       0.80      0.97      0.88        29\n\nScikit-learn treats each class as the positive class once.\n\nClass 0\n\nHere, class 0 is considered the positive class.\n\nSo,\n\nTP = 25\nFP = 1\nFN = 7\nPrecision (Class 0)\nPrecision\n0\n\t\u200b\n\n=\n25+1\n25\n\t\u200b\n\n=\n26\n25\n\t\u200b\n\n=0.9615\n\n≈ 0.96\n\nMeaning: Whenever the model predicts No Heart Disease (0), it is correct 96% of the time.\n\nRecall (Class 0)\nRecall\n0\n\t\u200b\n\n=\n25+7\n25\n\t\u200b\n\n=\n32\n25\n\t\u200b\n\n=0.78125\n\n≈ 0.78\n\nMeaning: Out of all 32 patients who actually had No Heart Disease, the model correctly identified 25.\n\nF1-score (Class 0)\nF1=\nP+R\n2PR\n\t\u200b\n\n\nSubstitute\n\nP=0.96,R=0.78\nF1=\n0.96+0.78\n2(0.96)(0.78)\n\t\u200b\n\n=0.86\nClass 1\n\nNow class 1 is considered the positive class.\n\nTP = 28\nFP = 7\nFN = 1\nPrecision\n28+7\n28\n\t\u200b\n\n=0.80\n\nThis means:\n\nWhen the model predicts Heart Disease, it is correct 80% of the time.\n\nRecall\n28+1\n28\n\t\u200b\n\n=0.9655\n\n≈ 0.97\n\nMeaning:\n\nOut of 29 patients who actually have heart disease, the model correctly found 28.\n\nOnly 1 patient was missed.\n\nF1-score\nF1=\n0.80+0.97\n2(0.80)(0.97)\n\t\u200b\n\n=0.88\nSupport\nsupport\n\n0   32\n1   29\n\nSupport is simply the number of actual samples belonging to each class.\n\n32 patients actually belong to class 0.\n29 patients actually belong to class 1.\n\nTotal\n\n32+29=61\n\nwhich matches your test set size.\n\nAccuracy\naccuracy 0.87\n\nAccuracy is\n\nTotal\nTP+TN\n\t\u200b\n\n=\n61\n28+25\n\t\u200b\n\n=\n61\n53\n\t\u200b\n\n=0.869\n\n≈ 87%\n\nSo the model correctly classified 53 out of 61 patients.\n\nMacro Average\nmacro avg\nprecision 0.88\nrecall    0.87\nf1-score  0.87\n\nMacro average is the simple average of the metrics for each class.\n\nPrecision:\n\n2\n0.96+0.80\n\t\u200b\n\n=0.88\n\nRecall:\n\n2\n0.78+0.97\n\t\u200b\n\n=0.875≈0.87\n\nF1:\n\n2\n0.86+0.88\n\t\u200b\n\n=0.87\n\nEach class contributes equally, regardless of how many samples it has.\n\nWeighted Average\nweighted avg\nprecision 0.88\nrecall    0.87\nf1-score  0.87\n\nWeighted average uses the support of each class as weights.\n\nFor precision:\n\n61\n(0.96×32)+(0.80×29)\n\t\u200b\n\n=0.88\n\nSince your classes are nearly balanced (32 vs. 29), the weighted averages are very close to the macro averages.\n\nWhat does this report tell you?\nAccuracy = 87%: The model performs well overall.\nClass 1 (heart disease) has very high recall (97%): the model misses very few heart disease cases (only 1 false negative). This is often desirable in medical diagnosis because missing a patient with the disease can have serious consequences.\nClass 1 precision is 80%: about 20% of the patients predicted to have heart disease are actually healthy (false positives).\nClass 0 precision is 96%: when the model predicts "no heart disease," it is almost always correct.\nClass 0 recall is 78%: the model incorrectly labels some healthy patients as having heart disease (7 false positives from the perspective of class 1).\n\nOverall, your Logistic Regression model is biased toward detecting heart disease, resulting in high recall for class 1 at the cost of a moderate number of false alarms. In a medical screening setting, this trade-off is often preferred because it is generally safer to investigate a healthy patient further than to miss someone who actually has the disease.\n'

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df1 = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/digit-recognizer/train.csv'